# Generated by Django 5.1.1 on 2024-11-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_user_email', models.EmailField(max_length=254)),
                ('request_song', models.CharField(max_length=100)),
                ('request_artist', models.CharField(max_length=100)),
                ('request_remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('playlist', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(upload_to='images')),
                ('audio', models.FileField(upload_to='audio')),
            ],
        ),
    ]
